foreach(program IN ITEMS "${SERVER}" "${FIXTURE}" "${CAPTURE}")
    get_filename_component(name "${program}" NAME)
    if(program STREQUAL CAPTURE)
        set(expected_error "ngm-capture:")
    else()
        set(expected_error "unsupported arguments")
    endif()
    execute_process(COMMAND "${program}" --version
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
    if(NOT result STREQUAL "0" OR NOT output STREQUAL "${name} ${EXPECTED_VERSION}\n" OR NOT error STREQUAL "")
        message(FATAL_ERROR "${name} version mismatch (${result}): stdout=[${output}] stderr=[${error}]")
    endif()
    execute_process(COMMAND "${program}" --help
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
    if(NOT result STREQUAL "0" OR NOT output MATCHES "Usage:" OR NOT error STREQUAL "")
        message(FATAL_ERROR "${name} help failed")
    endif()
    execute_process(COMMAND "${program}"
        INPUT_FILE /dev/null RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
    if(program STREQUAL SERVER)
        if(NOT result STREQUAL "0" OR NOT output STREQUAL "")
            message(FATAL_ERROR "${name} must handle clean stdin EOF without protocol output")
        endif()
    elseif(NOT result STREQUAL "2" OR NOT output STREQUAL "" OR NOT error MATCHES "${expected_error}")
        message(FATAL_ERROR "${name} must require explicit experiment inputs on stderr")
    endif()
    foreach(arguments IN ITEMS "--invalid" "--version;unexpected")
        execute_process(COMMAND "${program}" ${arguments}
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
        if(NOT result STREQUAL "2" OR NOT output STREQUAL "" OR NOT error MATCHES "${expected_error}")
            message(FATAL_ERROR "${name} accepted invalid arguments or polluted stdout")
        endif()
    endforeach()
endforeach()

# Provenance is parsed before any artifact root is opened or process launched.
# Reject excessive nesting before constructing a recursively deep JSON value.
set(scratch "${CMAKE_CURRENT_BINARY_DIR}/capture-cli-check")
file(MAKE_DIRECTORY "${scratch}")
string(REPEAT "[" 1024 prefix)
string(REPEAT "]" 1024 suffix)
file(WRITE "${scratch}/deep.json" "{\"data\":${prefix}0${suffix}}")
execute_process(COMMAND "${CAPTURE}" --provenance-json "${scratch}/deep.json"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
if(NOT result STREQUAL "2" OR NOT output STREQUAL "" OR NOT error MATCHES "exceeds 64 nested containers")
    message(FATAL_ERROR "Capture CLI did not reject overdeep provenance cleanly")
endif()
