file(MAKE_DIRECTORY "${SCRATCH}")
set(shader "${SCRATCH}/probe.vert")
set(binary "${SCRATCH}/probe.spv")
file(COPY_FILE "${PROJECT_ROOT}/tests/shaders/build.vert" "${shader}")
set(command "${CMAKE_COMMAND}" "-DCOMPILER=${COMPILER}" "-DSOURCE=${shader}" "-DOUTPUT=${binary}"
    -P "${PROJECT_ROOT}/cmake/CompileShader.cmake")
execute_process(COMMAND ${command} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 65)
if(NOT result STREQUAL "0" OR NOT EXISTS "${binary}")
    message(FATAL_ERROR "Initial shader compilation failed: ${output}${error}")
endif()
file(WRITE "${shader}" "#version 460\nvoid main() { syntax error }\n")
execute_process(COMMAND ${command} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 65)
if(result STREQUAL "0" OR NOT error MATCHES "GLSL compilation failed")
    message(FATAL_ERROR "Malformed shader must produce a useful failure: ${output}${error}")
endif()
if(EXISTS "${binary}" OR EXISTS "${binary}.tmp")
    message(FATAL_ERROR "Failed compilation left stale shader output")
endif()
# Paths containing spaces above and successful recovery use the same build rule.
file(COPY_FILE "${PROJECT_ROOT}/tests/shaders/build.vert" "${shader}")
execute_process(COMMAND ${command} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 65)
if(NOT result STREQUAL "0" OR NOT EXISTS "${binary}")
    message(FATAL_ERROR "Shader compilation did not recover: ${output}${error}")
endif()
