foreach(program IN ITEMS "${SERVER}" "${FIXTURE}")
    get_filename_component(name "${program}" NAME)
    execute_process(COMMAND "${program}" --version
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
    if(NOT result STREQUAL "0" OR NOT output STREQUAL "${name} ${EXPECTED_VERSION}\n" OR NOT error STREQUAL "")
        message(FATAL_ERROR "${name} version mismatch (${result}): stdout=[${output}] stderr=[${error}]")
    endif()
    execute_process(COMMAND "${program}" --help
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
    if(NOT result STREQUAL "0" OR NOT output MATCHES "Usage:" OR NOT error STREQUAL "")
        message(FATAL_ERROR "${name} help failed")
    endif()
    execute_process(COMMAND "${program}"
        INPUT_FILE /dev/null RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
    if(program STREQUAL SERVER)
        if(NOT result STREQUAL "0" OR NOT output STREQUAL "")
            message(FATAL_ERROR "${name} must handle clean stdin EOF without protocol output")
        endif()
    elseif(NOT result STREQUAL "2" OR NOT output STREQUAL "" OR NOT error MATCHES "unsupported arguments")
        message(FATAL_ERROR "${name} must require explicit experiment inputs on stderr")
    endif()
    foreach(arguments IN ITEMS "--invalid" "--version;unexpected")
        execute_process(COMMAND "${program}" ${arguments}
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
        if(NOT result STREQUAL "2" OR NOT output STREQUAL "" OR NOT error MATCHES "unsupported arguments")
            message(FATAL_ERROR "${name} accepted invalid arguments or polluted stdout")
        endif()
    endforeach()
endforeach()
