# Inspect real ELF consumers and the archives, rather than trusting build flags.
string(REPLACE "|" ";" binaries "${BINARIES}")
string(REPLACE "|" ";" archives "${ARCHIVES}")
foreach(binary IN LISTS binaries)
    execute_process(COMMAND "${READELF}" -d "${binary}"
        RESULT_VARIABLE result OUTPUT_VARIABLE dynamic ERROR_VARIABLE error)
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "Cannot inspect ${binary}: ${error}")
    endif()
    string(REGEX MATCHALL "\\(NEEDED\\)[^\n]*\\[[^]]+\\]" entries "${dynamic}")
    foreach(entry IN LISTS entries)
        string(REGEX REPLACE ".*\\[([^]]+)\\].*" "\\1" library "${entry}")
        if(NOT library MATCHES "^(lib(c|m|stdc\\+\\+|gcc_s|pthread|dl|rt)\\.so(\\.[0-9]+)*|ld-linux[^/]*\\.so(\\.[0-9]+)*)$")
            message(FATAL_ERROR "Undocumented dynamic dependency in ${binary}: ${library}")
        endif()
        message(STATUS "${binary}: ${library}")
    endforeach()
endforeach()
foreach(archive IN LISTS archives)
    execute_process(COMMAND "${AR}" t "${archive}"
        RESULT_VARIABLE result OUTPUT_VARIABLE members ERROR_VARIABLE error)
    if(NOT result STREQUAL "0" OR members STREQUAL "")
        message(FATAL_ERROR "Expected a nonempty source-built static archive: ${archive}: ${error}")
    endif()
endforeach()
