foreach(required IN ITEMS PROJECT_ROOT SHADER_DIR COMPILER PROJECT_VERSION HOST_COMPILER_ID HOST_COMPILER_VERSION BUILD_TYPE)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()

function(json_string output value)
    string(REPLACE "\\" "\\\\" escaped "${value}")
    string(REPLACE "\"" "\\\"" escaped "${escaped}")
    string(REPLACE "\n" "\\n" escaped "${escaped}")
    string(REPLACE "\r" "\\r" escaped "${escaped}")
    string(REPLACE "\t" "\\t" escaped "${escaped}")
    set(${output} "\"${escaped}\"" PARENT_SCOPE)
endfunction()

set(manifest "{\"schema_version\":1,\"source_revision\":\"unknown\",\"source_dirty\":null}")
json_string(value "${PROJECT_VERSION}")
string(JSON manifest SET "${manifest}" project_version "${value}")
find_program(GIT git)
if(GIT AND EXISTS "${PROJECT_ROOT}/.git")
    execute_process(COMMAND "${GIT}" -C "${PROJECT_ROOT}" rev-parse HEAD
        RESULT_VARIABLE result OUTPUT_VARIABLE revision ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(result EQUAL 0)
        json_string(value "${revision}")
        string(JSON manifest SET "${manifest}" source_revision "${value}")
    endif()
    execute_process(COMMAND "${GIT}" -C "${PROJECT_ROOT}" status --porcelain --untracked-files=normal
        RESULT_VARIABLE result OUTPUT_VARIABLE dirty ERROR_QUIET)
    if(result EQUAL 0)
        if(dirty STREQUAL "")
            string(JSON manifest SET "${manifest}" source_dirty false)
        else()
            string(JSON manifest SET "${manifest}" source_dirty true)
        endif()
    endif()
endif()
set(build "{}")
foreach(pair IN ITEMS "compiler_id|${HOST_COMPILER_ID}" "compiler_version|${HOST_COMPILER_VERSION}"
        "build_type|${BUILD_TYPE}" "cxx_flags|${HOST_COMPILER_FLAGS}")
    string(FIND "${pair}" "|" separator)
    string(SUBSTRING "${pair}" 0 ${separator} key)
    math(EXPR start "${separator} + 1")
    string(SUBSTRING "${pair}" ${start} -1 text)
    json_string(value "${text}")
    string(JSON build SET "${build}" "${key}" "${value}")
endforeach()
string(JSON manifest SET "${manifest}" build "${build}")
execute_process(COMMAND "${COMPILER}" --version RESULT_VARIABLE result OUTPUT_VARIABLE version ERROR_VARIABLE error
    OUTPUT_STRIP_TRAILING_WHITESPACE TIMEOUT 10)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Cannot identify source-built shader compiler: ${error}")
endif()
json_string(value "${version}")
set(shader_compiler "{\"arguments\":[\"-V\",\"--target-env\",\"vulkan1.3\",\"-g\",\"-Od\"]}")
string(JSON shader_compiler SET "${shader_compiler}" version "${value}")
file(SHA256 "${COMPILER}" compiler_hash)
string(JSON shader_compiler SET "${shader_compiler}" sha256 "\"${compiler_hash}\"")
string(JSON manifest SET "${manifest}" shader_compiler "${shader_compiler}")
set(shaders "[]")
set(index 0)
foreach(name IN ITEMS scene.vert scene.frag shader-error.frag indirect.vert bindless.frag post.vert post.frag)
    if(name MATCHES "\\.vert$")
        set(stage vertex)
    else()
        set(stage fragment)
    endif()
    file(SHA256 "${SHADER_DIR}/${name}" source_hash)
    file(SHA256 "${SHADER_DIR}/${name}.spv" binary_hash)
    set(shader "{\"stage\":\"${stage}\",\"source\":\"${name}\",\"spirv\":\"${name}.spv\",\"source_sha256\":\"${source_hash}\",\"spirv_sha256\":\"${binary_hash}\"}")
    string(JSON shaders SET "${shaders}" ${index} "${shader}")
    math(EXPR index "${index} + 1")
endforeach()
string(JSON manifest SET "${manifest}" shaders "${shaders}")
file(WRITE "${SHADER_DIR}/provenance.json.tmp" "${manifest}\n")
file(RENAME "${SHADER_DIR}/provenance.json.tmp" "${SHADER_DIR}/provenance.json")
