# The optional NGFX headers belong to the separately installed Nsight toolchain.
# No SDK source or binary is acquired by configure/build. Normal builds omit it.
set(NGM_NSIGHT_SDK_ROOT "" CACHE PATH "Optional NsightGraphicsSDK version directory for the fixture")

function(ngm_configure_fixture_sdk target)
    set(sdk_manifest "{\"compiled\":false,\"version\":null,\"source_bundle_sha256\":null,\"files\":[]}")
    set(sdk_enabled 0)
    if(NGM_NSIGHT_SDK_ROOT)
        if(NOT IS_ABSOLUTE "${NGM_NSIGHT_SDK_ROOT}")
            message(FATAL_ERROR "NGM_NSIGHT_SDK_ROOT must be an absolute SDK version directory")
        endif()
        file(REAL_PATH "${NGM_NSIGHT_SDK_ROOT}" sdk_root)
        foreach(required IN ITEMS LICENSE.txt include/NGFX_GraphicsCapture_Vulkan.h include/NGFX_Vulkan.h)
            if(NOT EXISTS "${sdk_root}/${required}")
                message(FATAL_ERROR "Missing ${required} in NGM_NSIGHT_SDK_ROOT; use the SDK from a matching Nsight installation")
            endif()
        endforeach()
        file(GLOB_RECURSE sdk_files CONFIGURE_DEPENDS RELATIVE "${sdk_root}" "${sdk_root}/include/*.h")
        list(APPEND sdk_files LICENSE.txt)
        list(SORT sdk_files)
        set(fingerprint "")
        set(records "[]")
        set(index 0)
        foreach(relative IN LISTS sdk_files)
            set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${sdk_root}/${relative}")
            file(SHA256 "${sdk_root}/${relative}" hash)
            string(APPEND fingerprint "${relative}:${hash}\n")
            string(JSON records SET "${records}" ${index} "{\"path\":\"${relative}\",\"sha256\":\"${hash}\"}")
            math(EXPR index "${index} + 1")
        endforeach()
        string(SHA256 bundle_hash "${fingerprint}")
        # Exact observed source bundles; labels are not inferred from directory names.
        if(bundle_hash STREQUAL "2acf4cc605a651ae7f0db91a5417b569aedf76763f9ebbac06c144ac455505b6")
            set(sdk_version "0.9.2")
        elseif(bundle_hash STREQUAL "73ac6585967dc22cd66d6d0e8b4d8ed8a3791a7b399f7824d28566ad79e556c5")
            set(sdk_version "0.9.0")
        else()
            message(FATAL_ERROR "Unqualified NGFX SDK source bundle ${bundle_hash}; retain and review its headers before adding a supported build profile")
        endif()
        set(sdk_enabled 1)
        set(sdk_manifest "{\"compiled\":true,\"version\":\"${sdk_version}\",\"source_bundle_sha256\":\"${bundle_hash}\",\"files\":${records}}")
        target_include_directories(${target} SYSTEM PRIVATE "${sdk_root}/include")
        target_link_libraries(${target} PRIVATE ${CMAKE_DL_LIBS})
    endif()
    set(sdk_dir "${CMAKE_CURRENT_BINARY_DIR}/generated/fixture-sdk")
    file(MAKE_DIRECTORY "${sdk_dir}")
    file(CONFIGURE OUTPUT "${sdk_dir}/SdkBuild.hpp" CONTENT
        "#pragma once\n#define NGM_FIXTURE_HAS_NSIGHT_SDK ${sdk_enabled}\nnamespace ngm::fixture { inline constexpr char sdk_build_json[] = R\"ngm_sdk(${sdk_manifest})ngm_sdk\"; }\n" @ONLY)
    file(CONFIGURE OUTPUT "${sdk_dir}/sdk-build.json" CONTENT "${sdk_manifest}\n" @ONLY)
    target_include_directories(${target} PRIVATE "${sdk_dir}")
    target_sources(${target} PRIVATE "${PROJECT_SOURCE_DIR}/src/fixture/SdkControl.cpp")
    set(NGM_FIXTURE_SDK_MANIFEST "${sdk_dir}/sdk-build.json" PARENT_SCOPE)
endfunction()
